const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.shadowlight,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Tween,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.MoveTo.Exps.MovingAngle,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.MoveTo.Acts.SetStopOnSolids,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName
	];
};
self.C3_JsPropNameTable = [
	{Variables: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{ShadowLight: 0},
	{Touch: 0},
	{Sine: 0},
	{bgSelector: 0},
	{btnArrowLeft: 0},
	{btnArrowRight: 0},
	{Nivel: 0},
	{ShadowCaster: 0},
	{btnNivel: 0},
	{pageIndicator: 0},
	{Tween: 0},
	{bgWin: 0},
	{Anchor: 0},
	{btnMenu: 0},
	{btnReset: 0},
	{btnSound: 0},
	{ScrollTo: 0},
	{camera: 0},
	{coin: 0},
	{coin_particle: 0},
	{win: 0},
	{defeat: 0},
	{gameManager: 0},
	{center: 0},
	{ground: 0},
	{sacar: 0},
	{Fade: 0},
	{hand: 0},
	{Bullet: 0},
	{particles: 0},
	{selected: 0},
	{fall: 0},
	{player: 0},
	{player_spr: 0},
	{destroybox: 0},
	{Solid: 0},
	{pozo: 0},
	{ground_dark: 0},
	{wall: 0},
	{btnPlay: 0},
	{nHoja: 0},
	{cam_selector: 0},
	{gameLogo: 0},
	{splashLogo: 0},
	{goGame: 0},
	{taptoplay: 0},
	{transition: 0},
	{txtBtnNivel: 0},
	{name: 0},
	{txtUI: 0},
	{MoveTo: 0},
	{Players: 0},
	{Buttons: 0},
	{posX: 0},
	{posY: 0},
	{Level: 0},
	{dragAngle: 0},
	{moveAngle: 0},
	{startX: 0},
	{startY: 0},
	{totStars: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0}
];

self.InstanceType = {
	Variables: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Touch: class extends self.IInstance {},
	bgSelector: class extends self.ISpriteInstance {},
	btnArrowLeft: class extends self.ISpriteInstance {},
	btnArrowRight: class extends self.ISpriteInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	pageIndicator: class extends self.ISpriteInstance {},
	bgWin: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	coin_particle: class extends self.ISpriteInstance {},
	gameManager: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	particles: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	player_spr: class extends self.ISpriteInstance {},
	pozo: class extends self.ISpriteInstance {},
	ground_dark: class extends self.ITiledBackgroundInstance {},
	wall: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	cam_selector: class extends self.ISpriteInstance {},
	gameLogo: class extends self.ISpriteInstance {},
	splashLogo: class extends self.ISpriteInstance {},
	taptoplay: class extends self.ISpriteInstance {},
	transition: class extends self.ISpriteInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	Players: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}